code/blog/urls.py
from django.urls import path
from . import views

app_name= 'blog'
urlpatterns=[
    path('',views.index,name='index'),
    path('blog/detail/<int:blog_id>',views.blog_detail,name='blog_detail'),
    path('blog/pub',views.pub_blog,name='pub_blog'),
    path('blog/comment',views.pub_comment,name='pub_comment'),
    path('search/',views.search,name='search'),

]

code/campus_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls')),
    path('auth/',include('myauth.urls')),
]

code/myauth/urls.py
from django.urls import path
from . import views

app_name= 'myauth'


urlpatterns=[
    path('login/',views.auth_login,name='auth_login'),
    path('register/',views.register,name='register'),
    path('captcha',views.send_email_captcha,name='captcha'),
    path('logout/',views.logout_1,name='logout'),


]

code/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>砺儒云论坛--{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/image1.png' %}" alt="" height="60">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">论坛简介</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">联系我们</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="get">
                <input type="search" name='q' class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            
            {% if user.is_authenticated %}
                <div class="dropdown text-end ms-3 me-3">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/image3.jpg' %}" alt="mdo" width="52" height="52" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'myauth:logout' %}">退出登录</a></li>
                    </ul>
        </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'myauth:auth_login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'myauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
                
            {% endif %}
  
        </div>
    </div>
</header>
<main class="container bg-primary-subtle p-4 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

code/templates/blog_detail.html
{% extends 'base.html' %}
{% block title %}博客详情{% endblock %}
{% block head %}{% endblock %}
{% block main %}
    <h1>{{ blog.title }}</h1>
    <hr>
    <div class="mt-2 justify-content-around">
        <img src="{% static 'image/image2.png' %}" class="rounded" alt="" height="30" width="30">
        <span class="ms-2">{{ blog.author }}</span>
        <span class="ms-5">{{ blog.pub_time|date:'Y年m月d日 h时i分' }}</span>
        <hr>
        <div class="py-3">
            {{ blog.content|safe }}
        </div>
        <hr>
        <div class="mt-3 mb-3">
            <h3>评论（{{ blog.comments.all|length }}）</h3>
            
            <form action="{% url 'blog:pub_comment' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="blog_id" value="{{ blog.id }}">
                <div class="mt-4">
                    <input type="text" class="form-control" name="content" placeholder='下面我简单喵两句'>
                </div>
                <div class="text-end">
                    <button type="submit" class="mt-3 btn btn-primary">评如论</button>
                </div>
            </form>
        </div>
    </div>
    <hr>
    <div class="mt-2">
        <ul class="list-group list-group-flush">
            {% for comment in blog.comments.all %}
            <li class="list-group-item mt-2">
                <div class="d-flex justify-content-between text-body-secondary mt-3">
                    <div class="user-info">
                        <img src="{% static 'image/image2.png' %}" class="rounded" alt="" height="40" width="40">
                        <span class="ms-2">{{ comment.author.username }}</span>
                    </div>
                    <div class="create-time" style="line-height:40px">{{ comment.pub_time|date:'Y年m月d日 h时i分' }}</div>
                </div>
                <div class="mt-3 mb-3">
                    {{ comment.content }}
                </div>
            </li>
                {% endfor %}
        </ul>
    </div>
{% endblock %}

code/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

code/templates/index.html
{% extends 'base.html' %}

{% block title %}校园博客{% endblock %}

{% block main %}
    <h1>博客列表</h1>
    <div class="row row-cols-3 row-gap-3">
    {% for blog in blogs %}
    	
    
    
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <a href="{% url 'blog:blog_detail' blog_id=blog.id %}">{{ blog.title }}</a>
                </div>
                <div class="card-body" style="height:120px">

                    <p class="card-text">{{ blog.content|striptags|truncatechars:50 }}</p>

                </div>
                <div class="card-footer text-body-secondary d-flex justify-content-between">
                    <div>
                        <img src="{% static 'image/image2.png' %}" class="rounded" alt="" height="30" width="30">
                        <span class="ms-2">{{ blog.author.username }}</span>
                    </div>
                    <div>
                        {{ blog.pub_time|date:'Y年m月d日 h时i分' }}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

code/templates/introduction.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>砺儒云论坛--{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap5/bootstrap.min.css' %}">
    <script src="{% static 'bootstrap5/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap5/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head %}{% endblock %}
</head>
<body>
<header class="p-3 text-bg-light border-bottom mb-3">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'image/image1.png' %}" alt="" height="60">
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="/" class="nav-link px-2 text-secondary">首页</a></li>
                <li><a href="{% url 'blog:pub_blog' %}" class="nav-link px-2 text-secondary">发布博客</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">论坛简介</a></li>
                <li><a href="#" class="nav-link px-2 text-secondary">联系我们</a></li>
            </ul>

            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search" action="{% url 'blog:search' %}" method="get">
                <input type="search" name='q' class="form-control " placeholder="搜索..." aria-label="Search">
            </form>
            
            {% if user.is_authenticated %}
                <div class="dropdown text-end ms-3 me-3">
                    <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="{% static 'image/image3.jpg' %}" alt="mdo" width="52" height="52" class="rounded-circle">
                    </a>
                    <ul class="dropdown-menu text-small" style="">
                        <li><a class="dropdown-item" href="{% url 'myauth:logout' %}">退出登录</a></li>
                    </ul>
        </div>
            {% else %}
                <div class="text-end">
                    <a href="{% url 'myauth:auth_login' %}" type="button" class="btn btn-outline-primary me-2">登录</a>
                    <a href="{% url 'myauth:register' %}" type="button" class="btn btn-primary">注册</a>
                </div>
                
            {% endif %}
  
        </div>
    </div>
</header>
<main class="container bg-primary-subtle p-4 rounded">
    {% block main %}{% endblock %}
</main>
</body>
</html>

code/templates/login.html
{% extends 'base.html' %}

{% block title %}登录{% endblock %}

{% block main %}
    
    <div style="max-width: 330px" class="m-auto"> 
        <h1>请登录</h1>
        <form action="" method="post">
            {% csrf_token %}
            <div class="md-3">
                <label class="mb-1 mt-1">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="请输入邮箱">
            </div>
            <div class="md-3">
                <label class="mb-1 mt-1">密码</label>
                <input type="password" name="password" class="form-control" placeholder="请输入密码">
            </div>
            <div class="form-check mt-2">
                <input class="form-check-input" type="checkbox" name="remember" value="1" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                记住我
                </label>
            </div>
            <div class="mt-2 mb-5">
                <button class="btn btn-primary w-100">登陆</button>
            </div>
        </form>
    </div>

{% endblock %}

code/templates/pub_blog.html
{% extends 'base.html' %}
{% block title %}发布博客{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'wangeditor/style.css' %}">
    <script src="{% static 'wangeditor/index.js' %}"></script>
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>

    <style>
        #editor—wrapper {
            border: 1px solid #ccc;
            z-index: 100; /* 按需定义 */
        }

        #toolbar-container {
            border-bottom: 1px solid #ccc;
        }

        #editor-container {
            height: 500px;
        }
    </style>
    <script src="{% static 'js/pub_blog.js' %}"></script>
{% endblock %}


{% block main %}
    <h1>发布博客</h1>
    <div class="mt-3">
        <form action="" method="POST">
        {% csrf_token %}
            <div class="mt-3 mb-3">
                <label class="form-label">标题</label>
                <input type="text" name="title" class="form-control">
            </div>
            <div class="mt-3 mb-3">
                <label class="form-label">类别</label>
                <select name="category" class="form-select" id="category-select">
                    {% for category in category %}
                        <option value="{{ category.id }}">{{ category.name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mt-3 mb-3">
                <label class="form-label">内容</label>
                <div id="editor-wrapper">
                    <div id="toolbar-container"><!-- 工具栏 --></div>
                    <div id="editor-container"><!-- 编辑器 --></div>
                </div>
            </div>
            <div class="mt-3 mb-3 text-end">
                <button class="btn btn-primary " id="submit-btn">发布</button>
            </div>


        </form>
    </div>
{% endblock %}

code/templates/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}

{% block head %}
    <script src="{% static 'jquery/jquery-3.7.1.min.js' %}"></script>
    <script src="{% static 'js/register.js' %}"></script>
    
{% endblock %}

{% block main %}
    <div style="max-width: 330px" class="m-auto"> 
        <h2>请注册</h2>
        <form action="" method="post">
            {% csrf_token %}
            <div class="md-3">
                <label class="mb-1 mt-1">用户名</label>
                <input type="text" name="username" class="form-control" placeholder="请输入用户名">
            </div>
            <div class="md-3">
                <label class="mb-1 mt-1">邮箱</label>
                <input type="email" name="email" class="form-control" placeholder="请输入邮箱">
            </div>
            <div class="md-3">
                <label class="mb-1 mt-1">密码</label>
                <input type="password" name="password" class="form-control" placeholder="请输入密码">
            </div>

            <div class="input-group mt-1 md-3">
                <label class="mb-1 mt-1">验证码</label>
                <div class="input-group">
                <input type="text" class="form-control" placeholder="请输入验证码" name="captcha"
                       aria-label="Recipient's username" aria-describedby="button-addon2">
                <button class="btn btn-outline-secondary" type="button" id="captcha" >发送验证码</button>
            </div>
            </div>
            
            <div class="mt-4 mb-5">
                <button class="btn btn-primary w-100">注册</button>
            </div>
            
        </form>
         
    </div>
{% endblock %}